/**
 * Regras de workflow técnico para Engenharia, Obras e Assistência
 */

import type { AutomationRule } from './WorkflowRules'

export const TECHNICAL_WORKFLOW_RULES: AutomationRule[] = [
  // ── ENGENHARIA ───────────────────────────────────────────────────────────

  {
    id: 'ENG01_LEVANTAMENTO_RECEBIDO',
    nome: 'Levantamento recebido pela Engenharia',
    descricao: 'Levantamento entrou para a fila de engenharia — atribui projetista e define SLA',
    ativo: true,
    prioridade: 1,
    gatilho: { entityType: 'PROJETO', statusNovo: 'AGUARDANDO ENGENHARIA' },
    acoes: [
      { tipo: 'CRIAR_TAREFA', params: { titulo: 'technical.tasks.eng.elaborarProjeto', responsavelRole: 'ENGENHARIA', slaHoras: 120 } },
      { tipo: 'ATRIBUIR_RESPONSAVEL', params: { responsavelRole: 'ENGENHARIA' } },
      { tipo: 'DEFINIR_SLA', params: { slaHoras: 120 } },
      { tipo: 'ATIVAR_CHECKLIST', params: { checklistItems: ['technical.checklist.eng.levantamento', 'technical.checklist.eng.especificacoes'] } },
      { tipo: 'NOTIFICAR', params: { titulo: 'technical.notif.eng.levantamentoRecebido', notificarRole: ['ENGENHARIA'] } },
      { tipo: 'REGISTRAR_TIMELINE', params: { mensagem: 'technical.timeline.eng.levantamentoRecebido' } },
      { tipo: 'REGISTRAR_AUDITORIA' },
      { tipo: 'ATUALIZAR_DASHBOARD' },
    ],
  },
  {
    id: 'ENG02_PROJETO_INICIADO',
    nome: 'Projeto hidráulico em desenvolvimento',
    descricao: 'Engenharia iniciou elaboração do projeto — ativa uploads técnicos',
    ativo: true,
    prioridade: 1,
    gatilho: { entityType: 'PROJETO', statusNovo: 'EM PROJETO' },
    acoes: [
      { tipo: 'ATIVAR_UPLOAD' },
      { tipo: 'ATIVAR_CHECKLIST', params: { checklistItems: ['technical.checklist.eng.planta', 'technical.checklist.eng.dwg', 'technical.checklist.eng.dxf', 'technical.checklist.eng.kmz'] } },
      { tipo: 'DEFINIR_SLA', params: { slaHoras: 96 } },
      { tipo: 'NOTIFICAR', params: { titulo: 'technical.notif.eng.projetoIniciado', notificarRole: ['ENGENHARIA', 'COMERCIAL'] } },
      { tipo: 'REGISTRAR_TIMELINE', params: { mensagem: 'technical.timeline.eng.projetoIniciado' } },
      { tipo: 'ATUALIZAR_DASHBOARD' },
    ],
  },
  {
    id: 'ENG03_REVISAO_SOLICITADA',
    nome: 'Revisão solicitada',
    descricao: 'Projeto em revisão — notifica projetista e redefine prazo',
    ativo: true,
    prioridade: 1,
    gatilho: { entityType: 'PROJETO', statusNovo: 'REVISAO' },
    acoes: [
      { tipo: 'CRIAR_TAREFA', params: { titulo: 'technical.tasks.eng.aplicarRevisao', responsavelRole: 'ENGENHARIA', slaHoras: 48 } },
      { tipo: 'DEFINIR_SLA', params: { slaHoras: 48 } },
      { tipo: 'NOTIFICAR', params: { titulo: 'technical.notif.eng.revisaoSolicitada', notificarRole: ['ENGENHARIA', 'ADMINISTRADOR'] } },
      { tipo: 'REGISTRAR_TIMELINE', params: { mensagem: 'technical.timeline.eng.revisaoSolicitada' } },
      { tipo: 'REGISTRAR_AUDITORIA' },
      { tipo: 'ATUALIZAR_DASHBOARD' },
    ],
  },
  {
    id: 'ENG04_MEMORIAL_PENDENTE',
    nome: 'Memorial descritivo pendente',
    descricao: 'Projeto pronto — aguarda memorial descritivo e lista de materiais',
    ativo: true,
    prioridade: 1,
    gatilho: { entityType: 'PROJETO', statusNovo: 'AGUARDANDO MEMORIAL' },
    acoes: [
      { tipo: 'CRIAR_TAREFA', params: { titulo: 'technical.tasks.eng.elaborarMemorial', responsavelRole: 'ENGENHARIA', slaHoras: 72 } },
      { tipo: 'ATIVAR_CHECKLIST', params: { checklistItems: ['technical.checklist.eng.memorial', 'technical.checklist.eng.materiais', 'technical.checklist.eng.orcamento'] } },
      { tipo: 'DEFINIR_SLA', params: { slaHoras: 72 } },
      { tipo: 'NOTIFICAR', params: { titulo: 'technical.notif.eng.memorialPendente', notificarRole: ['ENGENHARIA'] } },
      { tipo: 'REGISTRAR_TIMELINE', params: { mensagem: 'technical.timeline.eng.memorialPendente' } },
      { tipo: 'ATUALIZAR_DASHBOARD' },
    ],
  },
  {
    id: 'ENG05_PROJETO_COMPLETO',
    nome: 'Projeto completo — aguarda aprovação',
    descricao: 'Memorial e projeto prontos — solicita aprovação do gerente',
    ativo: true,
    prioridade: 1,
    gatilho: { entityType: 'PROJETO', statusNovo: 'PROJETO COMPLETO' },
    acoes: [
      { tipo: 'CRIAR_TAREFA', params: { titulo: 'technical.tasks.eng.aprovacaoGerente', responsavelRole: 'ADMINISTRADOR', slaHoras: 24 } },
      { tipo: 'NOTIFICAR', params: { titulo: 'technical.notif.eng.projetoCompleto', notificarRole: ['ADMINISTRADOR', 'COMERCIAL'] } },
      { tipo: 'REGISTRAR_TIMELINE', params: { mensagem: 'technical.timeline.eng.projetoCompleto' } },
      { tipo: 'REGISTRAR_AUDITORIA' },
      { tipo: 'DISPARAR_EVENTO', params: { eventoTipo: 'crm.workflow.completed' } },
      { tipo: 'ATUALIZAR_DASHBOARD' },
    ],
  },

  // ── OBRAS ────────────────────────────────────────────────────────────────

  {
    id: 'OBR01_AGUARDANDO_LIBERACAO',
    nome: 'Obra aguardando liberação financeira',
    descricao: 'Obra criada — aguarda liberação financeira para início',
    ativo: true,
    prioridade: 1,
    gatilho: { entityType: 'OBRA', statusNovo: 'OBRA_CRIADA' },
    acoes: [
      { tipo: 'CRIAR_TAREFA', params: { titulo: 'technical.tasks.obra.liberacaoFinanceira', responsavelRole: 'FINANCEIRO', slaHoras: 48 } },
      { tipo: 'NOTIFICAR', params: { titulo: 'technical.notif.obra.aguardandoLiberacao', notificarRole: ['FINANCEIRO', 'OBRAS'] } },
      { tipo: 'REGISTRAR_TIMELINE', params: { mensagem: 'technical.timeline.obra.criada' } },
      { tipo: 'ATUALIZAR_DASHBOARD' },
    ],
  },
  {
    id: 'OBR02_PROGRAMACAO',
    nome: 'Obra em programação',
    descricao: 'Obra liberada — programa equipe e define cronograma',
    ativo: true,
    prioridade: 1,
    gatilho: { entityType: 'OBRA', statusNovo: 'PLANEJAMENTO' },
    acoes: [
      { tipo: 'CRIAR_TAREFA', params: { titulo: 'technical.tasks.obra.designarEquipe', responsavelRole: 'OBRAS', slaHoras: 24 } },
      { tipo: 'ATIVAR_CHECKLIST', params: { checklistItems: ['technical.checklist.obra.equipe', 'technical.checklist.obra.materiais', 'technical.checklist.obra.cronograma'] } },
      { tipo: 'DEFINIR_SLA', params: { slaHoras: 360 } },
      { tipo: 'NOTIFICAR', params: { titulo: 'technical.notif.obra.programacao', notificarRole: ['OBRAS', 'ADMINISTRADOR'] } },
      { tipo: 'REGISTRAR_TIMELINE', params: { mensagem: 'technical.timeline.obra.programacao' } },
      { tipo: 'ATUALIZAR_DASHBOARD' },
    ],
  },
  {
    id: 'OBR03_EXECUCAO',
    nome: 'Obra em execução',
    descricao: 'Obra iniciada em campo — ativa diário, uploads e checklists de segurança',
    ativo: true,
    prioridade: 1,
    gatilho: { entityType: 'OBRA', statusNovo: 'EXECUCAO' },
    acoes: [
      { tipo: 'ATIVAR_UPLOAD' },
      { tipo: 'ATIVAR_CHECKLIST', params: { checklistItems: ['technical.checklist.obra.seguranca', 'technical.checklist.obra.epi', 'technical.checklist.obra.diario'] } },
      { tipo: 'NOTIFICAR', params: { titulo: 'technical.notif.obra.execucao', notificarRole: ['OBRAS', 'ADMINISTRADOR', 'COMERCIAL'] } },
      { tipo: 'REGISTRAR_TIMELINE', params: { mensagem: 'technical.timeline.obra.execucao' } },
      { tipo: 'ATUALIZAR_DASHBOARD' },
    ],
  },
  {
    id: 'OBR04_ACOMPANHAMENTO',
    nome: 'Obra em acompanhamento',
    descricao: 'Obra em acompanhamento — atualiza KPIs e verifica cronograma',
    ativo: true,
    prioridade: 1,
    gatilho: { entityType: 'OBRA', statusNovo: 'ACOMPANHAMENTO' },
    acoes: [
      { tipo: 'CRIAR_TAREFA', params: { titulo: 'technical.tasks.obra.atualizarKpis', responsavelRole: 'OBRAS', slaHoras: 24 } },
      { tipo: 'NOTIFICAR', params: { titulo: 'technical.notif.obra.acompanhamento', notificarRole: ['OBRAS'] } },
      { tipo: 'REGISTRAR_TIMELINE', params: { mensagem: 'technical.timeline.obra.acompanhamento' } },
      { tipo: 'ATUALIZAR_DASHBOARD' },
    ],
  },
  {
    id: 'OBR05_ENTREGA',
    nome: 'Obra em entrega técnica',
    descricao: 'Obra concluída em campo — inicia processo de entrega com checklist e fotos',
    ativo: true,
    prioridade: 1,
    gatilho: { entityType: 'OBRA', statusNovo: 'ENTREGA' },
    acoes: [
      { tipo: 'CRIAR_TAREFA', params: { titulo: 'technical.tasks.obra.checklistEntrega', responsavelRole: 'OBRAS', slaHoras: 24 } },
      { tipo: 'ATIVAR_CHECKLIST', params: { checklistItems: ['technical.checklist.obra.fotosFinais', 'technical.checklist.obra.assinatura', 'technical.checklist.obra.documentos', 'technical.checklist.obra.testes'] } },
      { tipo: 'ATIVAR_UPLOAD' },
      { tipo: 'NOTIFICAR', params: { titulo: 'technical.notif.obra.entrega', notificarRole: ['OBRAS', 'COMERCIAL', 'ADMINISTRADOR'] } },
      { tipo: 'REGISTRAR_TIMELINE', params: { mensagem: 'technical.timeline.obra.entrega' } },
      { tipo: 'ATUALIZAR_DASHBOARD' },
    ],
  },
  {
    id: 'OBR06_ENCERRAMENTO',
    nome: 'Obra encerrada',
    descricao: 'Assinatura coletada — obra encerrada e garantia ativada',
    ativo: true,
    prioridade: 1,
    gatilho: { entityType: 'OBRA', statusNovo: 'ENCERRAMENTO' },
    acoes: [
      { tipo: 'CRIAR_TAREFA', params: { titulo: 'technical.tasks.obra.abrirGarantia', responsavelRole: 'ASSISTENCIA', slaHoras: 24 } },
      { tipo: 'NOTIFICAR', params: { titulo: 'technical.notif.obra.encerrada', notificarRole: ['ASSISTENCIA', 'COMERCIAL', 'ADMINISTRADOR'] } },
      { tipo: 'REGISTRAR_TIMELINE', params: { mensagem: 'technical.timeline.obra.encerrada' } },
      { tipo: 'REGISTRAR_AUDITORIA' },
      { tipo: 'DISPARAR_EVENTO', params: { eventoTipo: 'crm.workflow.completed' } },
      { tipo: 'ATUALIZAR_DASHBOARD' },
    ],
  },

  // ── ASSISTÊNCIA ──────────────────────────────────────────────────────────

  {
    id: 'ASS01_CHAMADO_ABERTO',
    nome: 'Chamado de assistência aberto',
    descricao: 'Cliente solicitou assistência — abre chamado e notifica equipe',
    ativo: true,
    prioridade: 1,
    gatilho: { entityType: 'ASSISTENCIA', statusNovo: 'CHAMADO' },
    acoes: [
      { tipo: 'CRIAR_TAREFA', params: { titulo: 'technical.tasks.ass.triagem', responsavelRole: 'ASSISTENCIA', slaHoras: 4 } },
      { tipo: 'DEFINIR_SLA', params: { slaHoras: 4 } },
      { tipo: 'NOTIFICAR', params: { titulo: 'technical.notif.ass.chamadoAberto', notificarRole: ['ASSISTENCIA', 'ADMINISTRADOR'] } },
      { tipo: 'REGISTRAR_TIMELINE', params: { mensagem: 'technical.timeline.ass.chamadoAberto' } },
      { tipo: 'ATUALIZAR_DASHBOARD' },
    ],
  },
  {
    id: 'ASS02_TRIAGEM',
    nome: 'Triagem em andamento',
    descricao: 'Chamado em triagem — avalia prioridade e agenda técnico',
    ativo: true,
    prioridade: 1,
    gatilho: { entityType: 'ASSISTENCIA', statusNovo: 'TRIAGEM' },
    acoes: [
      { tipo: 'ATIVAR_CHECKLIST', params: { checklistItems: ['technical.checklist.ass.problema', 'technical.checklist.ass.historico', 'technical.checklist.ass.prioridade'] } },
      { tipo: 'DEFINIR_SLA', params: { slaHoras: 8 } },
      { tipo: 'REGISTRAR_TIMELINE', params: { mensagem: 'technical.timeline.ass.triagem' } },
      { tipo: 'ATUALIZAR_DASHBOARD' },
    ],
  },
  {
    id: 'ASS03_AGENDADO',
    nome: 'Visita técnica agendada',
    descricao: 'Técnico agendado para visita — notifica cliente e técnico',
    ativo: true,
    prioridade: 1,
    gatilho: { entityType: 'ASSISTENCIA', statusNovo: 'AGENDAMENTO' },
    acoes: [
      { tipo: 'AGENDAR_FOLLOWUP', params: { titulo: 'technical.followup.ass.visitaTecnica', slaHoras: 24 } },
      { tipo: 'NOTIFICAR', params: { titulo: 'technical.notif.ass.agendado', notificarRole: ['ASSISTENCIA', 'COMERCIAL'] } },
      { tipo: 'REGISTRAR_TIMELINE', params: { mensagem: 'technical.timeline.ass.agendado' } },
      { tipo: 'ATUALIZAR_DASHBOARD' },
    ],
  },
  {
    id: 'ASS04_TECNICO_CAMPO',
    nome: 'Técnico em campo',
    descricao: 'Técnico realizando manutenção — ativa uploads e diário',
    ativo: true,
    prioridade: 1,
    gatilho: { entityType: 'ASSISTENCIA', statusNovo: 'TECNICO_CAMPO' },
    acoes: [
      { tipo: 'ATIVAR_UPLOAD' },
      { tipo: 'ATIVAR_CHECKLIST', params: { checklistItems: ['technical.checklist.ass.pecas', 'technical.checklist.ass.ferramentas', 'technical.checklist.ass.epi'] } },
      { tipo: 'REGISTRAR_TIMELINE', params: { mensagem: 'technical.timeline.ass.tecnicoCampo' } },
      { tipo: 'ATUALIZAR_DASHBOARD' },
    ],
  },
  {
    id: 'ASS05_VALIDACAO',
    nome: 'Validação da manutenção',
    descricao: 'Manutenção concluída — valida com cliente antes de fechar',
    ativo: true,
    prioridade: 1,
    gatilho: { entityType: 'ASSISTENCIA', statusNovo: 'VALIDACAO' },
    acoes: [
      { tipo: 'ATIVAR_CHECKLIST', params: { checklistItems: ['technical.checklist.ass.testePos', 'technical.checklist.ass.aprovacaoCliente'] } },
      { tipo: 'NOTIFICAR', params: { titulo: 'technical.notif.ass.validacao', notificarRole: ['ASSISTENCIA'] } },
      { tipo: 'REGISTRAR_TIMELINE', params: { mensagem: 'technical.timeline.ass.validacao' } },
      { tipo: 'ATUALIZAR_DASHBOARD' },
    ],
  },
  {
    id: 'ASS06_FINALIZADO',
    nome: 'Assistência finalizada',
    descricao: 'Chamado encerrado — registra histórico e abre garantia',
    ativo: true,
    prioridade: 1,
    gatilho: { entityType: 'ASSISTENCIA', statusNovo: 'FINALIZADO' },
    acoes: [
      { tipo: 'REGISTRAR_AUDITORIA' },
      { tipo: 'NOTIFICAR', params: { titulo: 'technical.notif.ass.finalizado', notificarRole: ['ASSISTENCIA', 'COMERCIAL', 'ADMINISTRADOR'] } },
      { tipo: 'REGISTRAR_TIMELINE', params: { mensagem: 'technical.timeline.ass.finalizado' } },
      { tipo: 'DISPARAR_EVENTO', params: { eventoTipo: 'crm.workflow.completed' } },
      { tipo: 'ATUALIZAR_DASHBOARD' },
    ],
  },
  {
    id: 'ASS07_GARANTIA',
    nome: 'Garantia ativada',
    descricao: 'Período de garantia iniciado — define SLA e agenda follow-up',
    ativo: true,
    prioridade: 1,
    gatilho: { entityType: 'ASSISTENCIA', statusNovo: 'GARANTIA' },
    acoes: [
      { tipo: 'AGENDAR_FOLLOWUP', params: { titulo: 'technical.followup.ass.garantia', slaHoras: 720 } },
      { tipo: 'DEFINIR_SLA', params: { slaHoras: 2160 } },
      { tipo: 'NOTIFICAR', params: { titulo: 'technical.notif.ass.garantia', notificarRole: ['ASSISTENCIA', 'COMERCIAL'] } },
      { tipo: 'REGISTRAR_TIMELINE', params: { mensagem: 'technical.timeline.ass.garantia' } },
      { tipo: 'ATUALIZAR_DASHBOARD' },
    ],
  },
]

export const TECHNICAL_RULES_MAP = Object.fromEntries(
  TECHNICAL_WORKFLOW_RULES.map((r) => [r.id, r])
) as Record<string, (typeof TECHNICAL_WORKFLOW_RULES)[number]>
