import type { Permission } from '@/shared/auth/Permission'
import { UserRole } from '@/shared/auth/UserRoles'

const FULL_ACCESS: Permission = {
  dashboard: true,
  clientes: true,
  agenda: true,
  visitas: true,
  oportunidades: true,
  riego: true,
  imoto: true,
  engenharia: true,
  obras: true,
  assistencia: true,
  relatorios: true,
  administracao: true,
  configuracoes: true,
  editar: true,
  excluir: true,
  upload: true,
  download: true,
  anexos: true,
}

export const Permissions: Record<UserRole, Permission> = {
  [UserRole.ADMIN]: { ...FULL_ACCESS },
  [UserRole.GERENTE]: {
    ...FULL_ACCESS,
    configuracoes: false,
  },
  [UserRole.COMERCIAL]: {
    dashboard: true,
    clientes: true,
    agenda: true,
    visitas: true,
    oportunidades: true,
    riego: false,
    imoto: false,
    engenharia: false,
    obras: false,
    assistencia: false,
    relatorios: false,
    administracao: false,
    configuracoes: false,
    editar: true,
    excluir: true,
    upload: true,
    download: true,
    anexos: false,
  },
  [UserRole.ENGENHARIA]: {
    dashboard: true,
    clientes: false,
    agenda: false,
    visitas: false,
    oportunidades: false,
    riego: true,
    imoto: true,
    engenharia: true,
    obras: false,
    assistencia: false,
    relatorios: false,
    administracao: false,
    configuracoes: false,
    editar: true,
    excluir: false,
    upload: true,
    download: true,
    anexos: true,
  },
  [UserRole.OBRAS]: {
    dashboard: true,
    clientes: false,
    agenda: false,
    visitas: false,
    oportunidades: false,
    riego: false,
    imoto: false,
    engenharia: false,
    obras: true,
    assistencia: false,
    relatorios: false,
    administracao: false,
    configuracoes: false,
    editar: true,
    excluir: false,
    upload: true,
    download: true,
    anexos: true,
  },
  [UserRole.ASSISTENCIA]: {
    dashboard: true,
    clientes: false,
    agenda: false,
    visitas: false,
    oportunidades: false,
    riego: false,
    imoto: false,
    engenharia: false,
    obras: false,
    assistencia: true,
    relatorios: false,
    administracao: false,
    configuracoes: false,
    editar: true,
    excluir: false,
    upload: true,
    download: true,
    anexos: false,
  },
  [UserRole.FINANCEIRO]: {
    dashboard: true,
    clientes: false,
    agenda: false,
    visitas: false,
    oportunidades: false,
    riego: false,
    imoto: false,
    engenharia: false,
    obras: false,
    assistencia: false,
    relatorios: true,
    administracao: false,
    configuracoes: false,
    editar: false,
    excluir: false,
    upload: false,
    download: true,
    anexos: false,
  },
  [UserRole.VISUALIZADOR]: {
    dashboard: true,
    clientes: true,
    agenda: true,
    visitas: true,
    oportunidades: true,
    riego: true,
    imoto: true,
    engenharia: true,
    obras: true,
    assistencia: true,
    relatorios: true,
    administracao: false,
    configuracoes: false,
    editar: false,
    excluir: false,
    upload: false,
    download: true,
    anexos: true,
  },
}
