import type { EntityStatus } from '@/shared/types/core'

export const GLOBAL_STATUSES: EntityStatus[] = [
  'LEAD',
  'CLIENTE',
  'VISITA',
  'LEVANTAMENTO',
  'AGUARDANDO ENGENHARIA',
  'EM PROJETO',
  'AGUARDANDO MEMORIAL',
  'PROJETO COMPLETO',
  'ORÇAMENTO',
  'NEGOCIAÇÃO',
  'VENDIDO',
  'OBRA',
  'ENTREGUE',
  'GARANTIA',
  'ASSISTÊNCIA',
  'CANCELADO',
  'RASCUNHO',
  'ATIVO',
  'INATIVO',
  'EM_ANALISE',
  'ENVIADO',
  'APROVADO',
  'REPROVADO',
  'REVISAO',
  'OBRA_CRIADA',
  'PLANEJAMENTO',
  'EXECUCAO',
  'ACOMPANHAMENTO',
  'ENTREGA',
  'ENCERRAMENTO',
]

export const GLOBAL_STATUS_LABELS: Record<EntityStatus, string> = {
  LEAD: 'Lead',
  CLIENTE: 'Cliente',
  VISITA: 'Visita',
  LEVANTAMENTO: 'Levantamento',
  'AGUARDANDO ENGENHARIA': 'Aguardando engenharia',
  'EM PROJETO': 'Em projeto',
  'AGUARDANDO MEMORIAL': 'Aguardando memorial',
  'PROJETO COMPLETO': 'Projeto completo',
  'ORÇAMENTO': 'Orçamento',
  'NEGOCIAÇÃO': 'Negociação',
  VENDIDO: 'Vendido',
  OBRA: 'Obra',
  ENTREGUE: 'Entregue',
  GARANTIA: 'Garantia',
  'ASSISTÊNCIA': 'Assistência',
  CANCELADO: 'Cancelado',
  RASCUNHO: 'Rascunho',
  ATIVO: 'Ativo',
  INATIVO: 'Inativo',
  EM_ANALISE: 'Em analise',
  ENVIADO: 'Enviado',
  APROVADO: 'Aprovado',
  REPROVADO: 'Reprovado',
  REVISAO: 'Revisao',
  OBRA_CRIADA: 'Obra criada',
  PLANEJAMENTO: 'Planejamento',
  EXECUCAO: 'Execucao',
  ACOMPANHAMENTO: 'Acompanhamento',
  ENTREGA: 'Entrega',
  ENCERRAMENTO: 'Encerramento',
}
