import type { ImotoSegment, ImotoUploadCategory } from '@/modules/imoto/types/imotoTypes'

export const IMOTO_COLLECTIONS = {
  levantamentos: 'imoto_levantamentos',
} as const

export const IMOTO_STORAGE = {
  cacheLevantamentos: 'riagro.imoto.levantamentos.v3',
  draftForm: 'riagro.imoto.draft.v3',
} as const

export const IMOTO_SEGMENT_LABELS: Record<ImotoSegment, string> = {
  FABRICA_RACOES: 'Fabrica de Racoes',
  TRANSPORTADORES_RODOVIARIOS: 'Transportadores Rodoviarios',
}

export const IMOTO_MEDIA_FOLDER: Record<ImotoUploadCategory, string> = {
  FOTO: 'fotos',
  VIDEO: 'videos',
  PDF: 'pdfs',
  DWG: 'dwgs',
  DXF: 'dxfs',
  KMZ: 'kmzs',
}

export const IMOTO_MEDIA_KEYS = {
  FOTO: 'fotos',
  VIDEO: 'videos',
  PDF: 'pdfs',
  DWG: 'dwgs',
  DXF: 'dxfs',
  KMZ: 'kmzs',
} as const

type ImotoQuestion = { key: string; label: string; required?: boolean }

export const IMOTO_SEGMENT_QUESTIONS: Record<ImotoSegment, ImotoQuestion[]> = {
  FABRICA_RACOES: [
    { key: 'capacidadeProducaoDia', label: 'Capacidade de producao por dia (t)' },
    { key: 'tipoMisturador', label: 'Tipo de misturador principal' },
    { key: 'numeroSilos', label: 'Numero de silos de armazenamento' },
    { key: 'demandaAutomacao', label: 'Demanda de automacao industrial' },
    { key: 'nomeRepresentante', label: 'Nome do representante', required: false },
    { key: 'etapaObra', label: 'Etapa atual da obra', required: false },
    { key: 'nomeEmpresa', label: 'Nome da empresa', required: false },
    { key: 'nomeFantasia', label: 'Nome fantasia da empresa', required: false },
    { key: 'responsavelFabrica', label: 'Nome do responsável da fábrica', required: false },
    { key: 'nomeComprador', label: 'Nome do comprador', required: false },
    { key: 'telefoneResponsavel', label: 'Telefone do responsável', required: false },
    { key: 'telefoneComprador', label: 'Telefone do comprador', required: false },
    { key: 'emailResponsavel', label: 'E-mail do responsável', required: false },
    { key: 'emailComprador', label: 'E-mail do comprador', required: false },
    { key: 'cidade', label: 'Cidade', required: false },
    { key: 'localizacaoAreaConstrucao', label: 'Localização e área disponível para construção', required: false },
    { key: 'producaoDesejadaMes', label: 'Produção desejada por mês', required: false },
    { key: 'turnosTrabalho', label: 'Turnos de trabalho', required: false },
    { key: 'horasTrabalhoTurno', label: 'Horas de trabalho por turno', required: false },
    { key: 'diasTrabalhadosMes', label: 'Dias trabalhados no mês', required: false },
    { key: 'racaoGado', label: 'Tipos de ração para gado', required: false },
    { key: 'racaoAves', label: 'Tipos de ração para aves', required: false },
    { key: 'racaoSuinos', label: 'Tipos de ração para suínos', required: false },
    { key: 'racaoPetFilhotes', label: 'Tipos de ração para pets/filhotes', required: false },
    { key: 'armazenagemAtual', label: 'Forma de armazenagem atual', required: false },
    { key: 'produtosMaisUtilizados', label: 'Produtos mais utilizados', required: false },
    { key: 'armazenagemExterna', label: 'Detalhes da armazenagem externa', required: false },
    { key: 'armazenagemInterna', label: 'Detalhes da armazenagem interna', required: false },
    { key: 'diametroPeneiraNormal', label: 'Diâmetro da peneira para moagem normal', required: false },
    { key: 'diametroPeneiraFina', label: 'Diâmetro da peneira para moagem fina', required: false },
    { key: 'tipoMoagem', label: 'Tipo de moagem', required: false },
    { key: 'dosagem', label: 'Produtos dosados e forma de armazenagem', required: false },
    { key: 'tipoDosagem', label: 'Tipo de dosagem', required: false },
    { key: 'necessitaMoegaDosagem', label: 'Necessidade de moega para dosagem', required: false },
    { key: 'equipamentosDosagem', label: 'Equipamentos necessários para dosagem', required: false },
    { key: 'dosagemOleo', label: 'Dosagem de óleo e capacidade de armazenagem', required: false },
    { key: 'peletizacao', label: 'Peletização, extrusão ou laminação', required: false },
    { key: 'quantidadeSilosExpedicao', label: 'Quantidade de silos de expedição', required: false },
    { key: 'armazenagemRacaoPronta', label: 'Forma de armazenagem da ração pronta', required: false },
    { key: 'balancaRobo', label: 'Necessidade de balança robô', required: false },
    { key: 'quantidadeSilosEnsaque', label: 'Quantidade de silos para ensaque interno', required: false },
    { key: 'ensacadeira', label: 'Tipo de ensacadeira', required: false },
    { key: 'voltagem', label: 'Tipo de alimentação elétrica', required: false },
    { key: 'tensaoVoltagem', label: 'Tensão elétrica disponível', required: false },
  ],
  TRANSPORTADORES_RODOVIARIOS: [
    { key: 'capacidadeTransporteHora', label: 'Capacidade de transporte por hora (t/h)' },
    { key: 'comprimentoRotas', label: 'Comprimento total das rotas (m)' },
    { key: 'tipoAcionamento', label: 'Tipo de acionamento dos transportadores' },
    { key: 'pontosTransferencia', label: 'Quantidade de pontos de transferencia' },
    { key: 'nomeClienteImplemento', label: 'Nome do cliente', required: false },
    { key: 'cpfCnpj', label: 'CPF/CNPJ', required: false },
    { key: 'inscricaoEstadual', label: 'Inscrição estadual', required: false },
    { key: 'enderecoCliente', label: 'Endereço', required: false },
    { key: 'emailCliente', label: 'E-mail', required: false },
    { key: 'telefoneCliente', label: 'Telefone com DDD', required: false },
    { key: 'celularCliente', label: 'Celular com DDD', required: false },
    { key: 'marcaModeloVeiculo', label: 'Marca e modelo do veículo', required: false },
    { key: 'anoFabricacaoVeiculo', label: 'Ano de fabricação', required: false },
    { key: 'modeloCabine', label: 'Modelo da cabine', required: false },
    { key: 'tipoCabine', label: 'Tipo de cabine', required: false },
    { key: 'larguraChassi', label: 'Largura do chassi (m)', required: false },
    { key: 'configuracaoVeiculo', label: 'Configuração do veículo', required: false },
    { key: 'descricaoConfiguracaoVeiculo', label: 'Descrição de outra configuração do veículo', required: false },
    { key: 'dimensoesEntreEixos', label: 'Dimensões entre eixos (A, B, C, D, E, F e G)', required: false },
    { key: 'dimensaoEixoA', label: 'Dimensão entre eixos A (m)', required: false },
    { key: 'dimensaoEixoB', label: 'Dimensão entre eixos B (m)', required: false },
    { key: 'dimensaoEixoC', label: 'Dimensão entre eixos C (m)', required: false },
    { key: 'dimensaoEixoD', label: 'Dimensão entre eixos D (m)', required: false },
    { key: 'dimensaoEixoE', label: 'Dimensão entre eixos E (m)', required: false },
    { key: 'dimensaoEixoF', label: 'Dimensão entre eixos F (m)', required: false },
    { key: 'dimensaoEixoG', label: 'Dimensão entre eixos G (m)', required: false },
    { key: 'codigoCaixaCambio', label: 'Código da plaqueta da caixa de câmbio', required: false },
    { key: 'marcaCaixaCambio', label: 'Marca da caixa de câmbio', required: false },
    { key: 'quantidadeMarchas', label: 'Quantidade de marchas', required: false },
    { key: 'modeloTransmissao', label: 'Modelo de transmissão', required: false },
    { key: 'possuiTomadaForca', label: 'O veículo possui tomada de força', required: false },
    { key: 'sentidoTomadaForca', label: 'Sentido da tomada de força', required: false },
    { key: 'capacidadeCargaNecessaria', label: 'Capacidade de carga necessária', required: false },
    { key: 'numeroCaixas', label: 'Número de caixas necessárias', required: false },
    { key: 'dimensoesCaixas', label: 'Dimensões das caixas', required: false },
    { key: 'dimensaoCaixa1', label: 'Dimensão da caixa 1 (m)', required: false },
    { key: 'dimensaoCaixa2', label: 'Dimensão da caixa 2 (m)', required: false },
    { key: 'dimensaoCaixa3', label: 'Dimensão da caixa 3 (m)', required: false },
    { key: 'dimensaoCaixa4', label: 'Dimensão da caixa 4 (m)', required: false },
    { key: 'dimensaoCaixa5', label: 'Dimensão da caixa 5 (m)', required: false },
    { key: 'dimensaoCaixa6', label: 'Dimensão da caixa 6 (m)', required: false },
    { key: 'dimensaoCaixa7', label: 'Dimensão da caixa 7 (m)', required: false },
    { key: 'materialCarroceria', label: 'Material da carroceria', required: false },
    { key: 'corPredominante', label: 'Cor predominante da pintura (RAL)', required: false },
    { key: 'aplicacaoEspecialLogo', label: 'Aplicação especial e logo do cliente', required: false },
    { key: 'materialTransportado', label: 'Material que será transportado', required: false },
    { key: 'formaMaterialTransportado', label: 'Forma do material transportado', required: false },
    { key: 'carroceriaAdequada', label: 'Carroceria mais adequada para o cliente', required: false },
    { key: 'acionamentoTuboExpedicao', label: 'Acionamento do tubo de expedição', required: false },
    { key: 'comprimentoTuboExpedicao', label: 'Comprimento do tubo de expedição (m)', required: false },
    { key: 'alturaMaximaCarregamento', label: 'Altura máxima do carregamento (m)', required: false },
    { key: 'acionamentoTampasCaixas', label: 'Acionamento das tampas das caixas', required: false },
    { key: 'opcionaisImplemento', label: 'Opcionais do implemento', required: false },
    { key: 'responsavelVendas', label: 'Responsável de vendas', required: false },
    { key: 'responsavelInformativo', label: 'Responsável pelas informações', required: false },
  ],
}
